# Generated by Django 5.0 on 2023-12-15 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_curso_semestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='semestre',
        ),
        migrations.AddField(
            model_name='curso',
            name='id_semestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='cursos.semestre'),
        ),
    ]
