# Generated by Django 5.0 on 2023-12-15 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_remove_curso_semestre_curso_id_semestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='id_semestre',
        ),
        migrations.AddField(
            model_name='curso',
            name='semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.semestre'),
        ),
    ]
