# Generated by Django 5.0 on 2023-12-15 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_remove_curso_id_semestre_curso_semestre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={},
        ),
        migrations.AlterModelOptions(
            name='semestre',
            options={},
        ),
    ]
