# Generated by Django 5.0 on 2023-12-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_rename_id_semestre_semestre_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semestre',
            old_name='id',
            new_name='id_semestre',
        ),
    ]
